# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure PyPI Token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Update Poetry Lock File
        run: poetry lock --no-interaction

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Remove old builds
        run: rm -rf dist/ build/ loopsniff.egg-info/

      - name: Build package
        run: poetry build

      - name: Check build output
        run: ls -lh dist/

      - name: Publish package to PyPI
        run: poetry publish --build --no-interaction